// <auto-generated />
using CRUDApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUDApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250812083531_SeedCustomersData")]
    partial class SeedCustomersData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("CRUDApp.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Center",
                            City = "Tipasa",
                            FirstName = "Moh",
                            LastName = "Chami"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Addres2",
                            City = "Bouismail",
                            FirstName = "Amine",
                            LastName = "Salah"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Addres3",
                            City = "Alger",
                            FirstName = "Bilal",
                            LastName = "Mou"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
